import os
import klaus
from dulwich.repo import Repo

# Path to pre-built test repository generated by runtests.sh
TEST_REPO_PATH = os.path.join(os.path.dirname(__file__), "repos", "build", "test_repo")

def test_ephemeral_repo_tree_and_diff():
    """
    Test klaus tree, commit, and blob routes against the pre-built test_repo.
    """
    app = klaus.make_app([TEST_REPO_PATH], site_name="Test Site")
    client = app.test_client()

    repo_name = "test_repo"

    # Fetch HEAD commit SHA using dulwich
    dulwich_repo = Repo(TEST_REPO_PATH)
    head_sha = dulwich_repo.head().decode("utf-8")

    # 1. Landing / Index Page
    res = client.get("/")
    assert res.status_code == 200
    assert repo_name.encode() in res.data

    # 2. Repository History Page
    res = client.get(f"/{repo_name}/", follow_redirects=True)
    assert res.status_code == 200

    # 3. Tree View
    res = client.get(f"/{repo_name}/tree/{head_sha}/", follow_redirects=True)
    assert res.status_code == 200

    # 4. Commit View
    res = client.get(f"/{repo_name}/commit/{head_sha}/", follow_redirects=True)
    assert res.status_code == 200

    # 5. Blob View for test.c
    res = client.get(f"/{repo_name}/blob/{head_sha}/test.c", follow_redirects=True)
    assert res.status_code == 200